# Header
menu:
  Home: /
  My Works: /works
  About: /about
  Tags: /tags

rss: /atom.xml

title: CHAO LI's Blog

# User Info
user_name: CHAO LI
user_avatar: http://ol7zjjc80.bkt.clouddn.com/avatar.jpeg
user_location: Earth
user_description: "premature optimization is the root of all evil"
user_contact: lichaojacobs@tju.edu.cn
user_introduction: "混迹于互联网的落魄战士..."

github_username: lichaojacobs
twitter_username: lichaojacobs
weibo_username: 577448557
zhihu_username: chao-li-11
facebook_username: lichaojacobs
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# theme: icarus
theme: maupassant

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: true
livere_uid: MTAyMC8yOTg3MC82NDM1

use_disqus: true
disqus_url: https://jacobs-wanhb.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


# Deployment
language: zh-CN
deploy: 
  type: git
  repo: git@github.com:lichaojacobs/Blog.git
  branch: gh-pages

